name: "AppSweep Scan"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  appsweep-scan:
    name: AppSweep Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Upload with Gradle
      env:
        APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_API_KEY }}
      run: ./gradlew uploadToAppSweeprelease
