name: AppSweep Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  appsweep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build the Android app
        run: ./gradlew assembleDebug

      - name: Upload APK to AppSweep
        env:
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_API_KEY }}
        run: ./gradlew uploadToAppSweepRelease

  
          
